# Generated by Django 5.0.1 on 2024-01-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('DiseaseID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('ExamID', models.AutoField(primary_key=True, serialize=False)),
                ('ExamType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('ManagementID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseAlgorithm',
            fields=[
                ('AlgorithmID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecision', models.CharField(max_length=255)),
                ('DiseaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disease')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseAssessment',
            fields=[
                ('DiseaseAssessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecision', models.CharField(max_length=255)),
                ('DiseaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disease')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('HistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAssessment',
            fields=[
                ('HistoryAssessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecisions', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryWorkup',
            fields=[
                ('WorkupHxID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecision', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryManagement',
            fields=[
                ('HistoryManagementID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
                ('ManagementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.management')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='ManagementID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.management'),
        ),
        migrations.CreateModel(
            name='PE',
            fields=[
                ('PEID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='PEAssessment',
            fields=[
                ('PEID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecisions', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='PEManagement',
            fields=[
                ('PEManagementID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
                ('ManagementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.management')),
            ],
        ),
        migrations.CreateModel(
            name='PEWorkup',
            fields=[
                ('WorkupPEID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecision', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('TestID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='TestAssessment',
            fields=[
                ('TestAssessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecisions', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='TestManagement',
            fields=[
                ('TestManagementID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
                ('ManagementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.management')),
            ],
        ),
        migrations.CreateModel(
            name='TestWorkup',
            fields=[
                ('TestWorkupID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecision', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('VitalsID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='VitalsAssessment',
            fields=[
                ('VitalsID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecisions', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='VitalsManagement',
            fields=[
                ('VitalsManagementID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
                ('ManagementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.management')),
            ],
        ),
        migrations.CreateModel(
            name='VitalsWorkup',
            fields=[
                ('WorkupVitalsID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('NextDecision', models.CharField(max_length=255)),
                ('ConditionsForDecision', models.CharField(max_length=255)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
            ],
        ),
    ]
