# Generated by Django 5.0.1 on 2024-01-28 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='DiseaseID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='diseasealgorithm',
            old_name='AlgorithmID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='diseaseassessment',
            old_name='DiseaseAssessmentID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='examtype',
            old_name='ExamID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='HistoryID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='historyassessment',
            old_name='HistoryAssessmentID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='historymanagement',
            old_name='HistoryManagementID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='historyworkup',
            old_name='WorkupHxID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='management',
            old_name='ManagementID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='pe',
            old_name='PEID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='peassessment',
            old_name='PEID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='pemanagement',
            old_name='PEManagementID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='peworkup',
            old_name='WorkupPEID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='TestID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='testassessment',
            old_name='TestAssessmentID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='testmanagement',
            old_name='TestManagementID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='testworkup',
            old_name='TestWorkupID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='vitals',
            old_name='VitalsID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='vitalsassessment',
            old_name='VitalsID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='vitalsmanagement',
            old_name='VitalsManagementID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='vitalsworkup',
            old_name='WorkupVitalsID',
            new_name='ID',
        ),
        migrations.RemoveField(
            model_name='diseasealgorithm',
            name='ConditionsForDecision',
        ),
        migrations.RemoveField(
            model_name='diseasealgorithm',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='diseaseassessment',
            name='ConditionsForDecision',
        ),
        migrations.RemoveField(
            model_name='diseaseassessment',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='historyassessment',
            name='ConditionsForDecisions',
        ),
        migrations.RemoveField(
            model_name='historyassessment',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='historyworkup',
            name='ConditionsForDecision',
        ),
        migrations.RemoveField(
            model_name='historyworkup',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='peassessment',
            name='ConditionsForDecisions',
        ),
        migrations.RemoveField(
            model_name='peassessment',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='peworkup',
            name='ConditionsForDecision',
        ),
        migrations.RemoveField(
            model_name='peworkup',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='testassessment',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='testworkup',
            name='ConditionsForDecision',
        ),
        migrations.RemoveField(
            model_name='testworkup',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='vitalsassessment',
            name='ConditionsForDecisions',
        ),
        migrations.RemoveField(
            model_name='vitalsassessment',
            name='NextDecision',
        ),
        migrations.RemoveField(
            model_name='vitalsworkup',
            name='ConditionsForDecision',
        ),
        migrations.RemoveField(
            model_name='vitalsworkup',
            name='NextDecision',
        ),
        migrations.AddField(
            model_name='diseasealgorithm',
            name='AlgorithmStep',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseasealgorithm',
            name='ConditionsForNextAlgorithm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseasealgorithm',
            name='DiseaseName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseasealgorithm',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AddField(
            model_name='diseasealgorithm',
            name='NextAlgorithm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaseassessment',
            name='Assessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaseassessment',
            name='ConditionsForNextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaseassessment',
            name='DiseaseName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaseassessment',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AddField(
            model_name='diseaseassessment',
            name='NextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historyassessment',
            name='Assessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historyassessment',
            name='ConditionsForNextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historyassessment',
            name='NextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historyworkup',
            name='ConditionsForNextWorkup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historyworkup',
            name='NextWorkup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historyworkup',
            name='Workup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='peassessment',
            name='Assessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='peassessment',
            name='ConditionsForNextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='peassessment',
            name='NextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='peworkup',
            name='ConditionsForNextWorkup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='peworkup',
            name='NextWorkup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='peworkup',
            name='Workup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testassessment',
            name='Assessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testassessment',
            name='ConditionsForNextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testassessment',
            name='NextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testworkup',
            name='ConditionsForNextWorkup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testworkup',
            name='NextWorkup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testworkup',
            name='Workup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitalsassessment',
            name='Assessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitalsassessment',
            name='ConditionsForNextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitalsassessment',
            name='NextAssessment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitalsworkup',
            name='ConditionsForNextWorkup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitalsworkup',
            name='NextWorkup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitalsworkup',
            name='Workup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='ManagementID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.management'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='DiseaseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.disease'),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseassessment',
            name='DiseaseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.disease'),
        ),
        migrations.AlterField(
            model_name='diseaseassessment',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseassessment',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='diseaseassessment',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='ExamType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historyassessment',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='historyassessment',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historyassessment',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historyassessment',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historymanagement',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='historymanagement',
            name='ManagementID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.management'),
        ),
        migrations.AlterField(
            model_name='historymanagement',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historymanagement',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historymanagement',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historyworkup',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='historyworkup',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historyworkup',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historyworkup',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pe',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='pe',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pe',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='peassessment',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='peassessment',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='peassessment',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='peassessment',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pemanagement',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='pemanagement',
            name='ManagementID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.management'),
        ),
        migrations.AlterField(
            model_name='pemanagement',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pemanagement',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pemanagement',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='peworkup',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='peworkup',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='peworkup',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='peworkup',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='test',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testassessment',
            name='ConditionsForDecisions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testassessment',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='testassessment',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testassessment',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testassessment',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testmanagement',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='testmanagement',
            name='ManagementID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.management'),
        ),
        migrations.AlterField(
            model_name='testmanagement',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testmanagement',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testmanagement',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testworkup',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='testworkup',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testworkup',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testworkup',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsassessment',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='vitalsassessment',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsassessment',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsassessment',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsmanagement',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='vitalsmanagement',
            name='ManagementID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.management'),
        ),
        migrations.AlterField(
            model_name='vitalsmanagement',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsmanagement',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsmanagement',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsworkup',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='vitalsworkup',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsworkup',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vitalsworkup',
            name='Trigger',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
