# Generated by Django 5.0.1 on 2024-01-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_diseaseid_disease_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NextStep', models.TextField(null=True)),
                ('ConditionsForNextStep', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diseasealgorithm',
            name='ConditionsForNextAlgorithm',
        ),
        migrations.RemoveField(
            model_name='diseasealgorithm',
            name='NextAlgorithm',
        ),
        migrations.RemoveField(
            model_name='diseaseassessment',
            name='ConditionsForNextAssessment',
        ),
        migrations.RemoveField(
            model_name='diseaseassessment',
            name='NextAssessment',
        ),
        migrations.RemoveField(
            model_name='historyassessment',
            name='ConditionsForNextAssessment',
        ),
        migrations.RemoveField(
            model_name='historyassessment',
            name='NextAssessment',
        ),
        migrations.RemoveField(
            model_name='historyworkup',
            name='ConditionsForNextWorkup',
        ),
        migrations.RemoveField(
            model_name='historyworkup',
            name='NextWorkup',
        ),
        migrations.RemoveField(
            model_name='peassessment',
            name='ConditionsForNextAssessment',
        ),
        migrations.RemoveField(
            model_name='peassessment',
            name='NextAssessment',
        ),
        migrations.RemoveField(
            model_name='peworkup',
            name='ConditionsForNextWorkup',
        ),
        migrations.RemoveField(
            model_name='peworkup',
            name='NextWorkup',
        ),
        migrations.RemoveField(
            model_name='testassessment',
            name='ConditionsForDecisions',
        ),
        migrations.RemoveField(
            model_name='testassessment',
            name='ConditionsForNextAssessment',
        ),
        migrations.RemoveField(
            model_name='testassessment',
            name='NextAssessment',
        ),
        migrations.RemoveField(
            model_name='testworkup',
            name='ConditionsForNextWorkup',
        ),
        migrations.RemoveField(
            model_name='testworkup',
            name='NextWorkup',
        ),
        migrations.RemoveField(
            model_name='vitalsassessment',
            name='ConditionsForNextAssessment',
        ),
        migrations.RemoveField(
            model_name='vitalsassessment',
            name='NextAssessment',
        ),
        migrations.RemoveField(
            model_name='vitalsworkup',
            name='ConditionsForNextWorkup',
        ),
        migrations.RemoveField(
            model_name='vitalsworkup',
            name='NextWorkup',
        ),
        migrations.AddField(
            model_name='diseasealgorithm',
            name='NextSteps',
            field=models.ManyToManyField(related_name='disease_algorithm', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='diseaseassessment',
            name='NextSteps',
            field=models.ManyToManyField(related_name='disease_assessment', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='historyassessment',
            name='NextSteps',
            field=models.ManyToManyField(related_name='history_assessment', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='historyworkup',
            name='NextSteps',
            field=models.ManyToManyField(related_name='history_workup', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='peassessment',
            name='NextSteps',
            field=models.ManyToManyField(related_name='pe_assessment', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='peworkup',
            name='NextSteps',
            field=models.ManyToManyField(related_name='pe_workup', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='testassessment',
            name='NextSteps',
            field=models.ManyToManyField(related_name='test_assessment', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='testworkup',
            name='NextSteps',
            field=models.ManyToManyField(related_name='test_workup', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='vitalsassessment',
            name='NextSteps',
            field=models.ManyToManyField(related_name='vitals_assessment', to='main.nextstep'),
        ),
        migrations.AddField(
            model_name='vitalsworkup',
            name='NextSteps',
            field=models.ManyToManyField(related_name='vitals_workup', to='main.nextstep'),
        ),
    ]
