# Generated by Django 5.0.1 on 2024-01-31 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_nextstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymanagement',
            name='ManagementName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pemanagement',
            name='ManagementName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testmanagement',
            name='ManagementName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vitalsmanagement',
            name='ManagementName',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='DiseaseManagement',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('DiseaseName', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('Trigger', models.CharField(max_length=255)),
                ('ManagementName', models.CharField(max_length=255)),
                ('DiseaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disease')),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examtype')),
                ('ManagementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.management')),
                ('NextSteps', models.ManyToManyField(related_name='disease_managements', to='main.nextstep')),
            ],
        ),
    ]
