# Generated by Django 5.0.1 on 2024-02-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_historymanagement_managementname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='ManagementID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.management'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
