# Generated by Django 5.0.1 on 2024-02-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_disease_managementid_alter_disease_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasealgorithm',
            name='AlgorithmStep',
        ),
    ]
