# Generated by Django 5.0.1 on 2024-02-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_diseasealgorithm_algorithmstep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextstep',
            old_name='NextStep',
            new_name='NextStepName',
        ),
        migrations.AddField(
            model_name='nextstep',
            name='DiseaseAlgorithmStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diseasealgorithm'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='DiseaseAssessmentStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diseaseassessment'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='HistoryAssessmentStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.historyassessment'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='HistoryWorkupStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.historyworkup'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='PEAssessmentStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.peassessment'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='PEWorkupStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.peworkup'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='TestAssessmentStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testassessment'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='TestWorkupStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testworkup'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='VitalAssessmentStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vitalsassessment'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='VitalWorkupStepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vitalsworkup'),
        ),
    ]
