# Generated by Django 5.0.1 on 2024-02-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_nextstep_nextstep_nextstepname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstep',
            name='ExamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
    ]
