# Generated by Django 5.0.1 on 2024-02-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_nextstep_examid'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pe',
            name='Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
