# Generated by Django 5.0.1 on 2024-02-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_history_number_pe_number_test_number_vitals_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextstep',
            old_name='DiseaseAlgorithmStepID',
            new_name='NextStepDiseaseAlgorithmID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='DiseaseAssessmentStepID',
            new_name='NextStepDiseaseAssessmentID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='HistoryAssessmentStepID',
            new_name='NextStepHistoryAssessmentID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='HistoryWorkupStepID',
            new_name='NextStepHistoryWorkupID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='PEAssessmentStepID',
            new_name='NextStepPEAssessmentID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='PEWorkupStepID',
            new_name='NextStepPEWorkupID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='TestAssessmentStepID',
            new_name='NextStepTestAssessmentID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='TestWorkupStepID',
            new_name='NextStepTestWorkupID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='VitalAssessmentStepID',
            new_name='NextStepVitalAssessmentID',
        ),
        migrations.RenameField(
            model_name='nextstep',
            old_name='VitalWorkupStepID',
            new_name='NextStepVitalWorkupID',
        ),
        migrations.AddField(
            model_name='nextstep',
            name='NextStepDiseaseDiagnosisID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.disease'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='NumberConditionsForNextStep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='OperatorConditionForNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='SymptomHistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.history'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='SymptomPE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pe'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='SymptomTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test'),
        ),
        migrations.AddField(
            model_name='nextstep',
            name='SymptomVitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vitals'),
        ),
        migrations.AlterField(
            model_name='nextstep',
            name='ConditionsForNextStep',
            field=models.TextField(blank=True, null=True),
        ),
    ]
