# Generated by Django 5.0.3 on 2024-03-26 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_nextstep_numberconditionsfornextstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diseasealgorithm',
            name='Trigger',
        ),
        migrations.CreateModel(
            name='TriggerChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('Group', models.CharField(max_length=2)),
                ('SelectionAdditionalInfo', models.CharField(max_length=255, null=True)),
                ('SelectionType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.selectiontype')),
                ('SymptomTrigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.symptoms')),
            ],
        ),
        migrations.AddField(
            model_name='diseasealgorithm',
            name='Triggers',
            field=models.ManyToManyField(related_name='disease_algorithms', to='main.triggerchecklistitem'),
        ),
    ]
