# Generated by Django 5.0.3 on 2024-04-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_selectiontype_remove_diseasealgorithm_trigger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseassessment',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='diseasemanagement',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='historyassessment',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='historymanagement',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='historyworkup',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='peassessment',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='pemanagement',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='peworkup',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='testassessment',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='testmanagement',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='testworkup',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='vitalsassessment',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='vitalsmanagement',
            name='Trigger',
        ),
        migrations.RemoveField(
            model_name='vitalsworkup',
            name='Trigger',
        ),
        migrations.AddField(
            model_name='diseaseassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='disease_assessment', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='diseasemanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='disease_management', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='historyassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='history_assessment', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='historymanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='history_management', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='historyworkup',
            name='Triggers',
            field=models.ManyToManyField(related_name='history_workup', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='peassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='pe_assessment', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='pemanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='pe_management', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='peworkup',
            name='Triggers',
            field=models.ManyToManyField(related_name='pe_workup', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='testassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='test_assessment', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='testmanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='test_management', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='testworkup',
            name='Triggers',
            field=models.ManyToManyField(related_name='test_workup', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='vitalsassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='vital_assessment', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='vitalsmanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='vital_management', to='main.triggerchecklistitem'),
        ),
        migrations.AddField(
            model_name='vitalsworkup',
            name='Triggers',
            field=models.ManyToManyField(related_name='vitals_workup', to='main.triggerchecklistitem'),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Triggers',
            field=models.ManyToManyField(related_name='disease_algorithm', to='main.triggerchecklistitem'),
        ),
    ]
