# Generated by Django 5.0.3 on 2024-05-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_diseaseassessment_trigger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtype',
            old_name='ExamType',
            new_name='Name',
        ),
    ]
