# Generated by Django 5.0.3 on 2024-05-23 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_examtype_examtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.disease'),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='DiseaseName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='ExamType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examtype'),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='NextSteps',
            field=models.ManyToManyField(blank=True, null=True, related_name='disease_algorithm', to='main.nextstep'),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Triggers',
            field=models.ManyToManyField(blank=True, null=True, related_name='disease_algorithm', to='main.triggerchecklistitem'),
        ),
    ]
