# Generated by Django 5.0.3 on 2024-05-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_diseasealgorithm_disease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasealgorithm',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='ID',
        ),
        migrations.AddField(
            model_name='diseasealgorithm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptoms',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
