# Generated by Django 5.0.3 on 2024-05-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_diseasealgorithm_id_remove_symptoms_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='ID',
        ),
        migrations.AddField(
            model_name='examtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
