# Generated by Django 5.0.3 on 2024-05-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_examtype_id_examtype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='diseaseassessment',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='diseasemanagement',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='history',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='historyassessment',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='historymanagement',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='historyworkup',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='management',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='pe',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='peassessment',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='pemanagement',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='peworkup',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='testassessment',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='testmanagement',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='testworkup',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='vitalsassessment',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='vitalsmanagement',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='vitalsworkup',
            name='ID',
        ),
        migrations.AddField(
            model_name='disease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseaseassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasemanagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historymanagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyworkup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='management',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pemanagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peworkup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(

            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmanagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testworkup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitals',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalsassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalsmanagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalsworkup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
