# Generated by Django 5.0.3 on 2024-10-15 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_diagnosis_diseasealgorithm_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('Group', models.CharField(max_length=2)),
                ('SelectionAdditionalInfo', models.CharField(max_length=255, null=True)),
                ('SelectionType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.selectiontype')),
                ('SymptomTrigger', models.ManyToManyField(blank=True, null=True, to='main.symptoms')),
            ],
        ),
        migrations.AlterField(
            model_name='diseasealgorithm',
            name='Triggers',
            field=models.ManyToManyField(blank=True, null=True, related_name='disease_algorithm', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='diseaseassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='disease_assessment', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='diseasemanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='disease_management', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='historyassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='history_assessment', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='historymanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='history_management', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='historyworkup',
            name='Triggers',
            field=models.ManyToManyField(related_name='history_workup', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='peassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='pe_assessment', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='pemanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='pe_management', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='peworkup',
            name='Triggers',
            field=models.ManyToManyField(related_name='pe_workup', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='testassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='test_assessment', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='testmanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='test_management', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='testworkup',
            name='Triggers',
            field=models.ManyToManyField(related_name='test_workup', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='vitalsassessment',
            name='Triggers',
            field=models.ManyToManyField(related_name='vital_assessment', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='vitalsmanagement',
            name='Triggers',
            field=models.ManyToManyField(related_name='vital_management', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='vitalsworkup',
            name='Triggers',
            field=models.ManyToManyField(related_name='vitals_workup', to='main.triggerchecklist'),
        ),
        migrations.DeleteModel(
            name='TriggerChecklistItem',
        ),
    ]
