# Generated by Django 5.0.3 on 2024-10-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_triggerchecklist_alter_diseasealgorithm_triggers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerchecklist',
            name='SymptomTrigger',
        ),
        migrations.AddField(
            model_name='triggerchecklist',
            name='SymptomItems',
            field=models.ManyToManyField(blank=True, null=True, related_name='trigger_checklist', to='main.symptoms'),
        ),
    ]
