# Generated by Django 5.0.3 on 2024-10-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_triggerchecklist_symptomtrigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='AlgorithmTrigger',
            field=models.ManyToManyField(related_name='disease_alg_trigger', to='main.triggerchecklist'),
        ),
    ]
