# Generated by Django 5.0.3 on 2024-11-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_disease_algorithmtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerchecklist',
            name='ChecklistLogic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
