# Generated by Django 5.0.3 on 2024-11-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_triggerchecklist_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerchecklist',
            name='GeneralAdditionalInfo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
