# Generated by Django 5.0.3 on 2024-11-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_triggerchecklist_generaladditionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggerchecklist',
            name='GeneralAdditionalInfo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='triggerchecklist',
            name='SelectionAdditionalInfo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
