# Generated by Django 5.0.3 on 2025-01-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_triggerchecklist_generaladditionalinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerchecklist',
            name='SymptomItems',
        ),
        migrations.AddField(
            model_name='triggerchecklist',
            name='MandatoryNegativeSymptoms',
            field=models.ManyToManyField(blank=True, related_name='mandatory_negative_trigger_checklist', to='main.symptoms'),
        ),
        migrations.AddField(
            model_name='triggerchecklist',
            name='MandatoryPositiveSymptoms',
            field=models.ManyToManyField(blank=True, related_name='mandatory_positive_trigger_checklist', to='main.symptoms'),
        ),
        migrations.AddField(
            model_name='triggerchecklist',
            name='NegativeSymptoms',
            field=models.ManyToManyField(blank=True, related_name='negative_trigger_checklist', to='main.symptoms'),
        ),
        migrations.AddField(
            model_name='triggerchecklist',
            name='PositiveSymptoms',
            field=models.ManyToManyField(blank=True, related_name='positive_trigger_checklist', to='main.symptoms'),
        ),
    ]
