# Generated by Django 5.0.3 on 2025-03-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_triggerchecklist_symptomitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='RootAlgorithmNodes',
            field=models.ManyToManyField(related_name='diseases', to='main.diseasealgorithm'),
        ),
    ]
