# Generated by Django 5.0.3 on 2025-03-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_disease_rootalgorithmnodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='AlgorithmTrigger',
            field=models.ManyToManyField(blank=True, related_name='disease_alg_trigger', to='main.triggerchecklist'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='RootAlgorithmNodes',
            field=models.ManyToManyField(blank=True, related_name='root_diseases_algorithms', to='main.diseasealgorithm'),
        ),
    ]
