# Generated by Django 5.0.3 on 2025-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_disease_algorithmtrigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasealgorithm',
            name='Source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
