# Generated by Django 5.0.3 on 2025-05-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_diseasealgorithm_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerchecklist',
            name='Source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
