# Generated by Django 5.2.1 on 2025-05-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_triggerchecklist_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
