# Generated by Django 5.2.1 on 2025-07-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_symptoms_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='ManagementPlaceholder',
            field=models.TextField(blank=True, null=True),
        ),
    ]
